DBURL='mysql+mysqldb://develop:deadbeef@localhost/cbs?charset=utf8'
#DBURL='mysql://crms:crms@localhost/crmsdb?charset=utf8'
#DBURL='mysql://demo_user:demo_pwd@localhost/demo_db?charset=utf8'
#DBURL='oracle+cx_oracle://fos:fos@cbs.5181.me/cbs'
#DBURL='oracle+cx_oracle://fos:fos@10.252.113.12/cbs'
